import type { Metadata } from "next";

import { generateMetadataFromDoc } from "~/lib/utils/generateMetadataFromDoc";
import { DashboardContainer } from "../../_components/dashboard-container";
import { DashboardTitle } from "../../_components/dashboard-title";
import { PioneerDetails } from "../../_components/pioneer/details";

const metadata = {
  title: "X7 Pioneers",
  description:
    "Discover X7 Finance's NFT Marketplace: A specialized platform designed for the DeFi enthusiast. Our marketplace is home to exclusive Utility NFTs that provide holders with unique benefits and privileges within the X7 DeFi ecosystem. Trade and invest in these NFTs to unlock enhanced financial opportunities and potential returns. Experience the future of decentralized finance with X7 Finance's NFT Marketplace.",
  slug: "/dashboard/pioneer",
  section: "dashboard",
};

export function generateMetadata(): Metadata {
  return generateMetadataFromDoc(metadata);
}

export default function PioneerPage() {
  return (
    <div className="xl:max-w-none">
      <DashboardTitle
        title="X7 Pioneer Dashboard"
        subHeader="X7 Pioneer NFTs grant holders a cut of Ecosystem funds. Periodically, a percentage of all profits generated by the X7 ecosystem will be pushed to the Pioneer Smart contract, from there you can claim that reward anytime you choose. Early investors were airdropped these NFTs and they are tradeable once unlocked."
        primaryButton={{
          text: "Trade X7 Pioneer NFTs",
          href: "https://pro.opensea.io/collection/x7-pioneer",
        }}
      />
      <DashboardContainer>
        <section className="flex flex-1 flex-col">
          <div className="h-full border-t border-zinc-400 pb-20 pt-4 dark:border-zinc-800">
            <div className="mx-auto max-w-xl">
              <PioneerDetails />
            </div>
          </div>
        </section>
      </DashboardContainer>
    </div>
  );
}
