import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    PINATA_JWT: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_APP_ENV: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().min(1),
    NEXT_PUBLIC_ASSETS_URL: z.string().min(1),
    NEXT_PUBLIC_DOCSEARCH_API_KEY: z.string().min(1),
    NEXT_PUBLIC_DOCSEARCH_APP_ID: z.string().min(1),
    NEXT_PUBLIC_DOCSEARCH_INDEX_NAME: z.string().min(1),
    NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ETHER_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BSC_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_POLY_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_OPTI_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ARB_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BASE_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ETHER_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BSC_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_POLY_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_OPTI_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ARB_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BASE_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_OPTI_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ARB_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_POLY_TESTNET_RPC: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ARBITRUM_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_OPTIMISM_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_POLYGON_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC_FALLBACK: z.string().min(1),
    NEXT_PUBLIC_ALCHEMY_ID: z.string().min(1),
    NEXT_PUBLIC_GATEWAY_URL: z.string().min(1),
  },
  runtimeEnv: {
    NEXT_PUBLIC_GATEWAY_URL: process.env.NEXT_PUBLIC_GATEWAY_URL,
    NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_ASSETS_URL: process.env.NEXT_PUBLIC_ASSETS_URL,
    NEXT_PUBLIC_DOCSEARCH_APP_ID: process.env.NEXT_PUBLIC_DOCSEARCH_APP_ID,
    NEXT_PUBLIC_DOCSEARCH_API_KEY: process.env.NEXT_PUBLIC_DOCSEARCH_API_KEY,
    NEXT_PUBLIC_DOCSEARCH_INDEX_NAME:
      process.env.NEXT_PUBLIC_DOCSEARCH_INDEX_NAME,
    NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID:
      process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
    NEXT_PUBLIC_DEFAULT_ETHER_RPC: process.env.NEXT_PUBLIC_DEFAULT_ETHER_RPC,
    NEXT_PUBLIC_DEFAULT_BSC_RPC: process.env.NEXT_PUBLIC_DEFAULT_BSC_RPC,
    NEXT_PUBLIC_DEFAULT_POLY_RPC: process.env.NEXT_PUBLIC_DEFAULT_POLY_RPC,
    NEXT_PUBLIC_DEFAULT_OPTI_RPC: process.env.NEXT_PUBLIC_DEFAULT_OPTI_RPC,
    NEXT_PUBLIC_DEFAULT_ARB_RPC: process.env.NEXT_PUBLIC_DEFAULT_ARB_RPC,
    NEXT_PUBLIC_DEFAULT_BASE_RPC: process.env.NEXT_PUBLIC_DEFAULT_BASE_RPC,
    NEXT_PUBLIC_DEFAULT_ETHER_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_ETHER_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_BSC_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_BSC_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_POLY_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_POLY_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_OPTI_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_OPTI_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_ARB_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_ARB_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_BASE_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_BASE_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_OPTI_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_OPTI_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_ARB_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_ARB_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_POLY_TESTNET_RPC:
      process.env.NEXT_PUBLIC_DEFAULT_POLY_TESTNET_RPC,
    NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_BSC_TESTNET_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_ARBITRUM_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_ARBITRUM_TESTNET_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_OPTIMISM_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_OPTIMISM_TESTNET_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_POLYGON_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_POLYGON_TESTNET_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_BASE_TESTNET_RPC_FALLBACK,
    NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC_FALLBACK:
      process.env.NEXT_PUBLIC_DEFAULT_ETHER_TESTNET_RPC_FALLBACK,

    NEXT_PUBLIC_ALCHEMY_ID: process.env.NEXT_PUBLIC_ALCHEMY_ID,
    PINATA_JWT: process.env.PINATA_JWT,
  },
})
